export const SP_LIST_FAIL = 'SP_LIST_FAIL';
export const SP_LIST_SUCCESS= 'SP_LIST_SUCCESS';
export const SP_LIST_REQUEST = 'SP_LIST_REQUEST';

export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_SUCCESS= 'SERVICE_DETAIL_SUCCESS';
export const SERVICE_DETAIL_FAIL = 'SERVICE_DETAIL_FAIL';



