export const SP_LIST_FAIL = 'SP_LIST_FAIL';
export const SP_LIST_SUCCESS= 'SP_LIST_SUCCESS';
export const SP_LIST_REQUEST = 'SP_LIST_REQUEST';

export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_SUCCESS= 'SERVICE_DETAIL_SUCCESS';
export const SERVICE_DETAIL_FAIL = 'SERVICE_DETAIL_FAIL';



export const PRODUCT_SAVE_REQUEST= 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_FAIL= 'PRODUCT_SAVE_FAIL';
export const PRODUCT_SAVE_SUCCESS= 'PRODUCT_SAVE_SUCCESS'

export const SERVICE_DELETE_REQUEST='SERVICE_DELETE_REQUEST';
export const SERVICE_DELETE_SUCCESS= 'SERVICE_DELETE_SUCCESS' ;
export const SERVICE_DELETE_FAIL= 'SERVICE_DELETE_FAIL';